apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80           # Service port (used inside cluster)
      targetPort: 80     # Port exposed by container (inside pod)
      nodePort: 30080    # Optional: External port exposed on your Node (range 30000-32767)
  type: NodePort
